services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: web-app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: root
      DB_NAME: web-app
      DB_PORT: 5432
      DB_DIALECT: postgres
    depends_on:
      - db

volumes:
  postgres_data: